development:
  adapter: mysql
  username: root
  database: to_midi_development
  timeout: 5000
  
test:
  adapter: mysql
  database: to_midi_test
  username: root
  timeout: 5000

production:
  adapter: mysql
  database: to_midi_production
  username: root
  password: to_midi_production
  timeout: 5000
